var dir_0ed949cfaf2a554caaefa27979f8da10 =
[
    [ "all.hpp", "math_2optimization_2all_8hpp_source.html", null ],
    [ "armijo.hpp", "armijo_8hpp.html", "armijo_8hpp" ],
    [ "bfgs.hpp", "bfgs_8hpp.html", "bfgs_8hpp" ],
    [ "conjugategradient.hpp", "conjugategradient_8hpp.html", "conjugategradient_8hpp" ],
    [ "constraint.hpp", "constraint_8hpp.html", "constraint_8hpp" ],
    [ "costfunction.hpp", "costfunction_8hpp.html", "costfunction_8hpp" ],
    [ "differentialevolution.hpp", "differentialevolution_8hpp.html", "differentialevolution_8hpp" ],
    [ "endcriteria.hpp", "endcriteria_8hpp.html", "endcriteria_8hpp" ],
    [ "goldstein.hpp", "goldstein_8hpp.html", "goldstein_8hpp" ],
    [ "leastsquare.hpp", "leastsquare_8hpp.html", "leastsquare_8hpp" ],
    [ "levenbergmarquardt.hpp", "levenbergmarquardt_8hpp.html", "levenbergmarquardt_8hpp" ],
    [ "linesearch.hpp", "linesearch_8hpp.html", "linesearch_8hpp" ],
    [ "linesearchbasedmethod.hpp", "linesearchbasedmethod_8hpp.html", "linesearchbasedmethod_8hpp" ],
    [ "lmdif.hpp", "lmdif_8hpp.html", null ],
    [ "method.hpp", "method_8hpp.html", "method_8hpp" ],
    [ "problem.hpp", "problem_8hpp.html", "problem_8hpp" ],
    [ "projectedconstraint.hpp", "projectedconstraint_8hpp.html", "projectedconstraint_8hpp" ],
    [ "projectedcostfunction.hpp", "projectedcostfunction_8hpp.html", "projectedcostfunction_8hpp" ],
    [ "projection.hpp", "projection_8hpp.html", "projection_8hpp" ],
    [ "simplex.hpp", "simplex_8hpp.html", "simplex_8hpp" ],
    [ "simulatedannealing.hpp", "simulatedannealing_8hpp.html", "simulatedannealing_8hpp" ],
    [ "spherecylinder.hpp", "spherecylinder_8hpp.html", "spherecylinder_8hpp" ],
    [ "steepestdescent.hpp", "steepestdescent_8hpp.html", "steepestdescent_8hpp" ]
];